### PR TITLE
Develop-gp

### PR DESCRIPTION
**Pull request by papagiannakis**
/Blender/--> a basic GI sphere-based scene to mimic the RTInOneWeekend one. Just open in Blender 4 and press the Render button

/CG/basicRayTracing.ipyng, a jupyter notebook following book 1 of Shirley

/CG/basicRayTracingInAweekendAllinOne.py an all-in-one book 1 python program

/CG/Raytracing/ mostly data folder, to be also used for splitting a the single CG/basicRayTracingInAweekendAllinOne.py into several classes, modules under a new package (future work)

added back basic immidiate OpenGL4+GLSL init()-draw() jupyter notebooks:
- basicWindow.ipynb
- basicTriangle.ipynb
- basicCubeGUI.ipynb

### CODE REVIEW

**Review by kamarianakis — APPROVED** [review]
LGTM

**Comment by kamarianakis** [comment]
We should suggest people to install a specific list of VSCode extensions (python related, ppm viewer, etc.)

**Comment by kamarianakis** [comment]
Double checked by @aprotopsaltis, closing

**Comment by aprotopsaltis** [comment]
double checked, LGTM

**Pull request merged**
