### PR TITLE
Adding a new example

### PR DESCRIPTION
**Pull request by kamarianakis**

### CODE REVIEW

**Comment by kamarianakis** [comment]
@paulzik @aprotopsaltis

**Review by papagiannakis — CHANGES_REQUESTED** [review]
it is not a good example to follow as:
1. Light class violates ECSS: a light if it has other data inside should not be an entity but a component
2. Gameobject class is not an Entity as it contains inside other components
3. The main rendering loop is supposed to be very short. Instead it contains a big list of hacks to access light functionality. All these should be in a system. Systems are the ones that should be operating on Entity groups and Component data. I understand the temptation of direct scenegraph hacks but we should not encourage this in examples. Please rework it so that it includes all data accessors and scenegraph modifications in a System

**Review by papagiannakis — APPROVED** [review]
LGTM

**Review by papagiannakis — CHANGES_REQUESTED** [review]
please rework this

**Comment by paulzik** [comment]
To me it is not very nice that we have Lights as entities and not as components
It would be a very good ECS example if we implemented the Lights as Components. In this case we can add the pointLight to the Cubes as well.
Can we change the implementation to support this? With 2 light components AmbientLight and PointLight

**Pull request closed without merging**
