### PR TITLE
GravityBB & PointCloudToMesh Features

### PR DESCRIPTION
**Pull request by kamarianakis**
GravityBB: A Gravity System using bounding boxes
PointCloudToMesh: A function that takes a point cloud and evaluates a corresponding mesh

### CODE REVIEW

**Review by aprotopsaltis — COMMENTED** [review]
- Seems fine, except little issue that is generated when two objects are spawned in very close locations and intersecting each other. These two fall down together.
- pointcloud2mesh leaves a whole in the bottom of the bunny

**Review by aprotopsaltis — CHANGES_REQUESTED** [review]
additionally, the test does not open a window.

**Comment by kamarianakis** [comment]
- A more descriptive text was added, based on Stratos comments, mentioning that camera can be controlled in this example in a very specific way (explicit mouse controls or via the ECSS graph and the EntityCam1/2 trans component)

**Comment by kamarianakis** [comment]
- Tests are not opening windows, unless opening them from the testing tab, or clicking on the little icon next to each test def: 
image
- the open3d module used in pointcloudtomesh uses a pivoting radius, points that are further away than the threshold cannot be connected. So the result is not always a manifold using this approach.

**Review by aprotopsaltis — APPROVED** [review]

**Pull request merged**
