### PR TITLE
Add sphere-ray-in-CGA notebook

### PR DESCRIPTION
**Pull request by kamarianakis**
Adds a notebook that regards the sphere-ray intersection in CGA. The information presented can be used to create a CGA raytracer.

### CODE REVIEW

**Comment by stratosger** [comment]
I get some deprecation warnings in the basic imports section. Also the visualisation section creates a huge image (I was scrolling for a long time). At the beginning it could not be loaded, and I had to close and reopen the notebook several times until I was able to view it correctly. Maybe if it was a bit smaller?

**Comment by kamarianakis** [comment]
Deprecation warnings cannot be avoided, they regard numba which is included within the clifford package. Visualization in VSCode is known to create issues, I usually work jupyter notebooks that embed visualization via Terminal/Firefox. I will add this as a comment there.

**Review by aprotopsaltis — COMMENTED** [review]
I confirm the deprecation warnings and the long image. In my case the image was loaded in the first run.

**Comment by aprotopsaltis** [comment]
> I confirm the deprecation warnings and the long image. In my case the image was loaded in the first run.

actually, the first time I ran each script separately. When I use RunAll, the behavior mentioned by @stratosger is replicated.

**Comment by kamarianakis** [comment]
Comments addressed: I have made `draw` as an optional block, added a block that saves the scene in html format, added comment that draw may not look good on VSCode and offered some suggestions there.

**Comment by kamarianakis** [comment]
@stratosger @aprotopsaltis check and approve if you are ok with the new additions

**Pull request merged**
