### PR TITLE
Add mouse interaction

### PR DESCRIPTION
**Pull request by aprotopsaltis**

### CODE REVIEW

**Comment by aprotopsaltis** [comment]
Work in progress. @kamarianakis @paulzik let us check for errors and other issues. Documentation is on the way.

**Comment by kamarianakis** [comment]
LGTM

**Review by kamarianakis — APPROVED** [review]

**Comment by kamarianakis** [comment]
@paulzik I will wait your comments on whether all tests and examples work on Windows too.

**Comment by paulzik** [comment]
Can we make the camera controls more like unity and maya. In general all the systems use the same controls.
For me it is very difficult to navigate with the mouse
Middle click: pan
Alt and LClick: Rotate around the center point
Alt and RClick: Zoom in-out
Scroll: Zoom in-out
RClick only: Look at (looks around while on the same place)

Unfortunately you cannot do all of them using the trackpad
We can keep both setups

Also after a while the camera gets a weird yaw rotation to its axis resulting in difficulty to navigate around
The sensitivity needs a bit improvement eg the rotation goes a lot faster than the zoom

**Comment by aprotopsaltis** [comment]
Imgui event handler checks for L-click, that creates a conflict with the Maya-like behavior.

**Comment by kamarianakis** [comment]
As Antonis mentioned, it is quite difficult to properly detect if an imgui window is hovered over or not (e.g., https://github.com/ocornut/imgui/issues/52 ), which creates issues with dragging/scrolling/keyboard input/etc. I suggest we move this extra functionality over a separate feature branch, on top of this one.

**Comment by kamarianakis** [comment]
All examples and test files working as intended, bumping version to 1.1.0. Further issues to be identified. All existing tests also work as tests for the existing mouse interaction.

**Pull request merged**
